### ISSUE TITLE
Defining the default charset and collation settings for a consumer

### ISSUE THREAD

**Issue by nicksantamaria** [amazeeio/dbaas-operator#54]
Some applications have issues with certain charsets and collation settings. It would be great if the `MariaDBConsumer` CRD supported overriding this on a per-database level.

This might look like a `mariadbconsumer` having the following parameters

```
apiVersion: mariadb.amazee.io/v1
kind: MariaDBConsumer
spec:
  consumer:
    ...
    charset: utf8mb4
    collation: utf8mb4_unicode_ci
```

might result in the database being created like so -

```
CREATE DATABASE db_name CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
```
